import {
  Listing,
  Location,
  Features,
  ListingDetails,
  SleepingSituation,
  MaxGuests,
} from "../modals/Listing";
export const listings: Listing[] = [
  {
    id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    category: "Hiking",
    imageSrc: "/images/deyar.png",
    name: "jiyeh",
    title: "First Apartment",
    owner_id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    description: "Sample Apartment description",
    area_type: "Sample Area Type",
    area_size: "Sample Area Size",
    images: ["image_url_1", "image_url_2"],
    deyar_service_fee: "0",
    cleaning_fee: "0",
    location: {
      zip: "12345",
      area: "Sample Area",
      city: "Larnaca",
      state: "Sample State",
      county: "Sample County",
      address: "Sample Address",
      country: "Sample Country",
      latitude: 123.456,
      longitude: -78.91,
    },
    features: {
      feature1: "Sample Feature 1",
      feature2: "Sample Feature 2",
    },
    listing_details: {
      detail1: "Sample Detail 1",
      detail2: "Sample Detail 2",
    },
    sleeping_situation: {
      beds: 2,
      bedrooms: 1,
    },
    max_guests: {
      max_total: 10,
      max_infants: 5,
      max_childAndAdults: 5,
    },
    nbOfGuestsAdded: true,
    createdAt: "2024-02-27T11:50:06.830Z",
    updatedAt: "2024-02-27T11:50:06.830Z",
  },
  {
    id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    category: "Hiking",
    imageSrc: "/images/deyar.png",
    name: "jiyeh",
    title: "First Apartment",
    owner_id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    description: "Sample Apartment description",
    area_type: "Sample Area Type",
    area_size: "Sample Area Size",
    images: ["image_url_1", "image_url_2"],
    deyar_service_fee: "0",
    cleaning_fee: "0",
    location: {
      zip: "12345",
      area: "Sample Area",
      city: "Larnaca",
      state: "Sample State",
      county: "Sample County",
      address: "Sample Address",
      country: "Sample Country",
      latitude: 123.456,
      longitude: -78.91,
    },
    features: {
      feature1: "Sample Feature 1",
      feature2: "Sample Feature 2",
    },
    listing_details: {
      detail1: "Sample Detail 1",
      detail2: "Sample Detail 2",
    },
    sleeping_situation: {
      beds: 2,
      bedrooms: 1,
    },
    max_guests: {
      max_total: 10,
      max_infants: 5,
      max_childAndAdults: 5,
    },
    nbOfGuestsAdded: true,
    createdAt: "2024-02-27T11:50:06.830Z",
    updatedAt: "2024-02-27T11:50:06.830Z",
  },
  {
    id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    category: "Hiking",
    imageSrc: "/images/deyar.png",
    name: "jiyeh",
    title: "First Apartment",
    owner_id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    description: "Sample Apartment description",
    area_type: "Sample Area Type",
    area_size: "Sample Area Size",
    images: ["image_url_1", "image_url_2"],
    deyar_service_fee: "0",
    cleaning_fee: "0",
    location: {
      zip: "12345",
      area: "Sample Area",
      city: "Larnaca",
      state: "Sample State",
      county: "Sample County",
      address: "Sample Address",
      country: "Sample Country",
      latitude: 123.456,
      longitude: -78.91,
    },
    features: {
      feature1: "Sample Feature 1",
      feature2: "Sample Feature 2",
    },
    listing_details: {
      detail1: "Sample Detail 1",
      detail2: "Sample Detail 2",
    },
    sleeping_situation: {
      beds: 2,
      bedrooms: 1,
    },
    max_guests: {
      max_total: 10,
      max_infants: 5,
      max_childAndAdults: 5,
    },
    nbOfGuestsAdded: true,
    createdAt: "2024-02-27T11:50:06.830Z",
    updatedAt: "2024-02-27T11:50:06.830Z",
  },
  {
    id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    category: "Hiking",
    imageSrc: "/images/deyar.png",
    name: "jiyeh",
    title: "First Apartment",
    owner_id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    description: "Sample Apartment description",
    area_type: "Sample Area Type",
    area_size: "Sample Area Size",
    images: ["image_url_1", "image_url_2"],
    deyar_service_fee: "0",
    cleaning_fee: "0",
    location: {
      zip: "12345",
      area: "Sample Area",
      city: "Larnaca",
      state: "Sample State",
      county: "Sample County",
      address: "Sample Address",
      country: "Sample Country",
      latitude: 123.456,
      longitude: -78.91,
    },
    features: {
      feature1: "Sample Feature 1",
      feature2: "Sample Feature 2",
    },
    listing_details: {
      detail1: "Sample Detail 1",
      detail2: "Sample Detail 2",
    },
    sleeping_situation: {
      beds: 2,
      bedrooms: 1,
    },
    max_guests: {
      max_total: 10,
      max_infants: 5,
      max_childAndAdults: 5,
    },
    nbOfGuestsAdded: true,
    createdAt: "2024-02-27T11:50:06.830Z",
    updatedAt: "2024-02-27T11:50:06.830Z",
  },
  {
    id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    category: "Hiking",
    imageSrc: "/images/deyar.png",
    name: "jiyeh",
    title: "First Apartment",
    owner_id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    description: "Sample Apartment description",
    area_type: "Sample Area Type",
    area_size: "Sample Area Size",
    images: ["image_url_1", "image_url_2"],
    deyar_service_fee: "0",
    cleaning_fee: "0",
    location: {
      zip: "12345",
      area: "Sample Area",
      city: "Larnaca",
      state: "Sample State",
      county: "Sample County",
      address: "Sample Address",
      country: "Sample Country",
      latitude: 123.456,
      longitude: -78.91,
    },
    features: {
      feature1: "Sample Feature 1",
      feature2: "Sample Feature 2",
    },
    listing_details: {
      detail1: "Sample Detail 1",
      detail2: "Sample Detail 2",
    },
    sleeping_situation: {
      beds: 2,
      bedrooms: 1,
    },
    max_guests: {
      max_total: 10,
      max_infants: 5,
      max_childAndAdults: 5,
    },
    nbOfGuestsAdded: true,
    createdAt: "2024-02-27T11:50:06.830Z",
    updatedAt: "2024-02-27T11:50:06.830Z",
  },
  {
    id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    category: "Hiking",
    imageSrc: "/images/deyar.png",
    name: "jiyeh",
    title: "First Apartment",
    owner_id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    description: "Sample Apartment description",
    area_type: "Sample Area Type",
    area_size: "Sample Area Size",
    images: ["image_url_1", "image_url_2"],
    deyar_service_fee: "0",
    cleaning_fee: "0",
    location: {
      zip: "12345",
      area: "Sample Area",
      city: "Larnaca",
      state: "Sample State",
      county: "Sample County",
      address: "Sample Address",
      country: "Sample Country",
      latitude: 123.456,
      longitude: -78.91,
    },
    features: {
      feature1: "Sample Feature 1",
      feature2: "Sample Feature 2",
    },
    listing_details: {
      detail1: "Sample Detail 1",
      detail2: "Sample Detail 2",
    },
    sleeping_situation: {
      beds: 2,
      bedrooms: 1,
    },
    max_guests: {
      max_total: 10,
      max_infants: 5,
      max_childAndAdults: 5,
    },
    nbOfGuestsAdded: true,
    createdAt: "2024-02-27T11:50:06.830Z",
    updatedAt: "2024-02-27T11:50:06.830Z",
  },
  {
    id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    category: "Hiking",
    imageSrc: "/images/deyar.png",
    name: "jiyeh",
    title: "First Apartment",
    owner_id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    description: "Sample Apartment description",
    area_type: "Sample Area Type",
    area_size: "Sample Area Size",
    images: ["image_url_1", "image_url_2"],
    deyar_service_fee: "0",
    cleaning_fee: "0",
    location: {
      zip: "12345",
      area: "Sample Area",
      city: "Larnaca",
      state: "Sample State",
      county: "Sample County",
      address: "Sample Address",
      country: "Sample Country",
      latitude: 123.456,
      longitude: -78.91,
    },
    features: {
      feature1: "Sample Feature 1",
      feature2: "Sample Feature 2",
    },
    listing_details: {
      detail1: "Sample Detail 1",
      detail2: "Sample Detail 2",
    },
    sleeping_situation: {
      beds: 2,
      bedrooms: 1,
    },
    max_guests: {
      max_total: 10,
      max_infants: 5,
      max_childAndAdults: 5,
    },
    nbOfGuestsAdded: true,
    createdAt: "2024-02-27T11:50:06.830Z",
    updatedAt: "2024-02-27T11:50:06.830Z",
  },
  {
    id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    category: "Hiking",
    imageSrc: "/images/deyar.png",
    name: "jiyeh",
    title: "First Apartment",
    owner_id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    description: "Sample Apartment description",
    area_type: "Sample Area Type",
    area_size: "Sample Area Size",
    images: ["image_url_1", "image_url_2"],
    deyar_service_fee: "0",
    cleaning_fee: "0",
    location: {
      zip: "12345",
      area: "Sample Area",
      city: "Larnaca",
      state: "Sample State",
      county: "Sample County",
      address: "Sample Address",
      country: "Sample Country",
      latitude: 123.456,
      longitude: -78.91,
    },
    features: {
      feature1: "Sample Feature 1",
      feature2: "Sample Feature 2",
    },
    listing_details: {
      detail1: "Sample Detail 1",
      detail2: "Sample Detail 2",
    },
    sleeping_situation: {
      beds: 2,
      bedrooms: 1,
    },
    max_guests: {
      max_total: 10,
      max_infants: 5,
      max_childAndAdults: 5,
    },
    nbOfGuestsAdded: true,
    createdAt: "2024-02-27T11:50:06.830Z",
    updatedAt: "2024-02-27T11:50:06.830Z",
  },
  {
    id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    category: "Hiking",
    imageSrc: "/images/deyar.png",
    name: "jiyeh",
    title: "First Apartment",
    owner_id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    description: "Sample Apartment description",
    area_type: "Sample Area Type",
    area_size: "Sample Area Size",
    images: ["image_url_1", "image_url_2"],
    deyar_service_fee: "0",
    cleaning_fee: "0",
    location: {
      zip: "12345",
      area: "Sample Area",
      city: "Larnaca",
      state: "Sample State",
      county: "Sample County",
      address: "Sample Address",
      country: "Sample Country",
      latitude: 123.456,
      longitude: -78.91,
    },
    features: {
      feature1: "Sample Feature 1",
      feature2: "Sample Feature 2",
    },
    listing_details: {
      detail1: "Sample Detail 1",
      detail2: "Sample Detail 2",
    },
    sleeping_situation: {
      beds: 2,
      bedrooms: 1,
    },
    max_guests: {
      max_total: 10,
      max_infants: 5,
      max_childAndAdults: 5,
    },
    nbOfGuestsAdded: true,
    createdAt: "2024-02-27T11:50:06.830Z",
    updatedAt: "2024-02-27T11:50:06.830Z",
  },
  {
    id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    category: "Hiking",
    imageSrc: "/images/deyar.png",
    name: "jiyeh",
    title: "First Apartment",
    owner_id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    description: "Sample Apartment description",
    area_type: "Sample Area Type",
    area_size: "Sample Area Size",
    images: ["image_url_1", "image_url_2"],
    deyar_service_fee: "0",
    cleaning_fee: "0",
    location: {
      zip: "12345",
      area: "Sample Area",
      city: "Larnaca",
      state: "Sample State",
      county: "Sample County",
      address: "Sample Address",
      country: "Sample Country",
      latitude: 123.456,
      longitude: -78.91,
    },
    features: {
      feature1: "Sample Feature 1",
      feature2: "Sample Feature 2",
    },
    listing_details: {
      detail1: "Sample Detail 1",
      detail2: "Sample Detail 2",
    },
    sleeping_situation: {
      beds: 2,
      bedrooms: 1,
    },
    max_guests: {
      max_total: 10,
      max_infants: 5,
      max_childAndAdults: 5,
    },
    nbOfGuestsAdded: true,
    createdAt: "2024-02-27T11:50:06.830Z",
    updatedAt: "2024-02-27T11:50:06.830Z",
  },
  {
    id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    category: "Hiking",
    imageSrc: "/images/deyar.png",
    name: "jiyeh",
    title: "First Apartment",
    owner_id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    description: "Sample Apartment description",
    area_type: "Sample Area Type",
    area_size: "Sample Area Size",
    images: ["image_url_1", "image_url_2"],
    deyar_service_fee: "0",
    cleaning_fee: "0",
    location: {
      zip: "12345",
      area: "Sample Area",
      city: "Larnaca",
      state: "Sample State",
      county: "Sample County",
      address: "Sample Address",
      country: "Sample Country",
      latitude: 123.456,
      longitude: -78.91,
    },
    features: {
      feature1: "Sample Feature 1",
      feature2: "Sample Feature 2",
    },
    listing_details: {
      detail1: "Sample Detail 1",
      detail2: "Sample Detail 2",
    },
    sleeping_situation: {
      beds: 2,
      bedrooms: 1,
    },
    max_guests: {
      max_total: 10,
      max_infants: 5,
      max_childAndAdults: 5,
    },
    nbOfGuestsAdded: true,
    createdAt: "2024-02-27T11:50:06.830Z",
    updatedAt: "2024-02-27T11:50:06.830Z",
  },
  {
    id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    category: "Hiking",
    imageSrc: "/images/deyar.png",
    name: "jiyeh",
    title: "First Apartment",
    owner_id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    description: "Sample Apartment description",
    area_type: "Sample Area Type",
    area_size: "Sample Area Size",
    images: ["image_url_1", "image_url_2"],
    deyar_service_fee: "0",
    cleaning_fee: "0",
    location: {
      zip: "12345",
      area: "Sample Area",
      city: "Larnaca",
      state: "Sample State",
      county: "Sample County",
      address: "Sample Address",
      country: "Sample Country",
      latitude: 123.456,
      longitude: -78.91,
    },
    features: {
      feature1: "Sample Feature 1",
      feature2: "Sample Feature 2",
    },
    listing_details: {
      detail1: "Sample Detail 1",
      detail2: "Sample Detail 2",
    },
    sleeping_situation: {
      beds: 2,
      bedrooms: 1,
    },
    max_guests: {
      max_total: 10,
      max_infants: 5,
      max_childAndAdults: 5,
    },
    nbOfGuestsAdded: true,
    createdAt: "2024-02-27T11:50:06.830Z",
    updatedAt: "2024-02-27T11:50:06.830Z",
  },
  {
    id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    category: "Hiking",
    imageSrc: "/images/deyar.png",
    name: "jiyeh",
    title: "First Apartment",
    owner_id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    description: "Sample Apartment description",
    area_type: "Sample Area Type",
    area_size: "Sample Area Size",
    images: ["image_url_1", "image_url_2"],
    deyar_service_fee: "0",
    cleaning_fee: "0",
    location: {
      zip: "12345",
      area: "Sample Area",
      city: "Larnaca",
      state: "Sample State",
      county: "Sample County",
      address: "Sample Address",
      country: "Sample Country",
      latitude: 123.456,
      longitude: -78.91,
    },
    features: {
      feature1: "Sample Feature 1",
      feature2: "Sample Feature 2",
    },
    listing_details: {
      detail1: "Sample Detail 1",
      detail2: "Sample Detail 2",
    },
    sleeping_situation: {
      beds: 2,
      bedrooms: 1,
    },
    max_guests: {
      max_total: 10,
      max_infants: 5,
      max_childAndAdults: 5,
    },
    nbOfGuestsAdded: true,
    createdAt: "2024-02-27T11:50:06.830Z",
    updatedAt: "2024-02-27T11:50:06.830Z",
  },
  {
    id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    category: "Hiking",
    imageSrc: "/images/deyar.png",
    name: "jiyeh",
    title: "First Apartment",
    owner_id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    description: "Sample Apartment description",
    area_type: "Sample Area Type",
    area_size: "Sample Area Size",
    images: ["image_url_1", "image_url_2"],
    deyar_service_fee: "0",
    cleaning_fee: "0",
    location: {
      zip: "12345",
      area: "Sample Area",
      city: "Larnaca",
      state: "Sample State",
      county: "Sample County",
      address: "Sample Address",
      country: "Sample Country",
      latitude: 123.456,
      longitude: -78.91,
    },
    features: {
      feature1: "Sample Feature 1",
      feature2: "Sample Feature 2",
    },
    listing_details: {
      detail1: "Sample Detail 1",
      detail2: "Sample Detail 2",
    },
    sleeping_situation: {
      beds: 2,
      bedrooms: 1,
    },
    max_guests: {
      max_total: 10,
      max_infants: 5,
      max_childAndAdults: 5,
    },
    nbOfGuestsAdded: true,
    createdAt: "2024-02-27T11:50:06.830Z",
    updatedAt: "2024-02-27T11:50:06.830Z",
  },
  {
    id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    category: "Hiking",
    imageSrc: "/images/deyar.png",
    name: "jiyeh",
    title: "First Apartment",
    owner_id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    description: "Sample Apartment description",
    area_type: "Sample Area Type",
    area_size: "Sample Area Size",
    images: ["image_url_1", "image_url_2"],
    deyar_service_fee: "0",
    cleaning_fee: "0",
    location: {
      zip: "12345",
      area: "Sample Area",
      city: "Larnaca",
      state: "Sample State",
      county: "Sample County",
      address: "Sample Address",
      country: "Sample Country",
      latitude: 123.456,
      longitude: -78.91,
    },
    features: {
      feature1: "Sample Feature 1",
      feature2: "Sample Feature 2",
    },
    listing_details: {
      detail1: "Sample Detail 1",
      detail2: "Sample Detail 2",
    },
    sleeping_situation: {
      beds: 2,
      bedrooms: 1,
    },
    max_guests: {
      max_total: 10,
      max_infants: 5,
      max_childAndAdults: 5,
    },
    nbOfGuestsAdded: true,
    createdAt: "2024-02-27T11:50:06.830Z",
    updatedAt: "2024-02-27T11:50:06.830Z",
  },
  {
    id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    category: "Hiking",
    imageSrc: "/images/deyar.png",
    name: "jiyeh",
    title: "First Apartment",
    owner_id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
    description: "Sample Apartment description",
    area_type: "Sample Area Type",
    area_size: "Sample Area Size",
    images: ["image_url_1", "image_url_2"],
    deyar_service_fee: "0",
    cleaning_fee: "0",
    location: {
      zip: "12345",
      area: "Sample Area",
      city: "Larnaca",
      state: "Sample State",
      county: "Sample County",
      address: "Sample Address",
      country: "Sample Country",
      latitude: 123.456,
      longitude: -78.91,
    },
    features: {
      feature1: "Sample Feature 1",
      feature2: "Sample Feature 2",
    },
    listing_details: {
      detail1: "Sample Detail 1",
      detail2: "Sample Detail 2",
    },
    sleeping_situation: {
      beds: 2,
      bedrooms: 1,
    },
    max_guests: {
      max_total: 10,
      max_infants: 5,
      max_childAndAdults: 5,
    },
    nbOfGuestsAdded: true,
    createdAt: "2024-02-27T11:50:06.830Z",
    updatedAt: "2024-02-27T11:50:06.830Z",
  },
];
export const singleList = {
  id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
  category: "Skiing",
  imageSrc: "/images/deyar.png",
  name: "jiyeh",
  title: "First Apartment",
  owner_id: "d09e7c1a-425b-4d10-97e0-f0cea35b2e70",
  description: "Sample Apartment description",
  area_type: "Sample Area Type",
  area_size: "Sample Area Size",
  images: ["image_url_1", "image_url_2"],
  deyar_service_fee: "0",
  cleaning_fee: "0",
  location: {
    zip: "12345",
    area: "Sample Area",
    city: "Larnaca",
    state: "Sample State",
    county: "Sample County",
    address: "Sample Address",
    country: "Sample Country",
    latitude: 123.456,
    longitude: -78.91,
  },
  features: {
    feature1: "Sample Feature 1",
    feature2: "Sample Feature 2",
  },
  listing_details: {
    detail1: "Sample Detail 1",
    detail2: "Sample Detail 2",
  },
  sleeping_situation: {
    beds: 2,
    bedrooms: 1,
  },
  max_guests: {
    max_total: 10,
    max_infants: 5,
    max_childAndAdults: 5,
  },

  nbOfGuestsAdded: true,
  createdAt: "2024-02-27T11:50:06.830Z",
  updatedAt: "2024-02-27T11:50:06.830Z",
};
